name: push to s3 bucket

on:
  push:
    branches:
      - master

jobs:
  deployment-to-s3:
    
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/setup-node@v4

      - name: List current directory contents  
        run: ls -la
     
      - name: Install node
        uses: actions/setup-node@v4
        with: 
         node-version: "20"

      # - name: List current directory contents  
      #   run: ls -la  
         
      - name: Change to project directory  
        run: cd /home/runner/work/Portfolio-/portfolio-
        
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Install AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Upload to S3  
        run: |  
          aws s3 sync ./build s3://tomilade-oyebola-tries-to-deploy --delete
